### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fromYukki** [iFixit/Matryoshka#12]
Hello guys

First of all - thank you for your great work! 
The second - could you be so kind to create new release? I see that the last one was about year ago and it is 25 commits after it came to the master branch. May it is time to create new release?

Thank you

**Comment by marczych** [comment]
Thank you for the kind words!

I just released [v0.2](https://github.com/iFixit/Matryoshka/releases/tag/v0.2) which is available on [Packagist](https://packagist.org/packages/ifixit/matryoshka).

--------

Let me know if you have any feedback on the library!
